// src/core/errors/codes.ts
/**
 * Canonical error codes for the UJAMAADAO platform
 * These codes are returned in API responses for client-side error handling
 */

export const UJAMAADAO_ERROR_CODES = {
  // ========== VALIDATION ERRORS (400) ==========
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // ========== AUTHENTICATION ERRORS (401) ==========
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  WALLET_SIGNATURE_INVALID: 'WALLET_SIGNATURE_INVALID',

  // ========== AUTHORIZATION ERRORS (403) ==========
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INSUFFICIENT_VERIFICATION: 'INSUFFICIENT_VERIFICATION',
  INSUFFICIENT_IMPACT_POINTS: 'INSUFFICIENT_IMPACT_POINTS',
  RESIDENCE_CHANGE_COOLDOWN: 'RESIDENCE_CHANGE_COOLDOWN',

  // ========== GEOGRAPHIC ERRORS (403) ==========
  GEOGRAPHIC_ERROR: 'GEOGRAPHIC_ERROR',
  INSUFFICIENT_GEOGRAPHIC_SCOPE: 'INSUFFICIENT_GEOGRAPHIC_SCOPE',
  GEOGRAPHIC_IDENTIFIER_MISMATCH: 'GEOGRAPHIC_IDENTIFIER_MISMATCH',
  MISSING_GEOGRAPHIC_CONTEXT: 'MISSING_GEOGRAPHIC_CONTEXT',

  // ========== ECONOMIC ERRORS (403/500) ==========
  ECONOMIC_ERROR: 'ECONOMIC_ERROR',
  INSUFFICIENT_TOKENS: 'INSUFFICIENT_TOKENS',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  WALLET_ERROR: 'WALLET_ERROR',
  INSUFFICIENT_PARTICIPATION_RIGHTS: 'INSUFFICIENT_PARTICIPATION_RIGHTS',

  // ========== RESOURCE ERRORS (404/409) ==========
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',

  // ========== SYSTEM ERRORS (500+) ==========
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type UjamaadaoErrorCode = typeof UJAMAADAO_ERROR_CODES[keyof typeof UJAMAADAO_ERROR_CODES];

/**
 * Helper to check if a string is a valid error code
 */
export function isValidErrorCode(code: string): code is UjamaadaoErrorCode {
  return Object.values(UJAMAADAO_ERROR_CODES).includes(code as UjamaadaoErrorCode);
}

/**
 * Map error codes to HTTP status codes
 */
export const ERROR_CODE_TO_STATUS: Record<UjamaadaoErrorCode, number> = {
  // 400s - Client errors
  [UJAMAADAO_ERROR_CODES.VALIDATION_ERROR]: 400,
  [UJAMAADAO_ERROR_CODES.INVALID_INPUT]: 400,
  [UJAMAADAO_ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,

  // 401s - Authentication
  [UJAMAADAO_ERROR_CODES.AUTHENTICATION_ERROR]: 401,
  [UJAMAADAO_ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [UJAMAADAO_ERROR_CODES.TOKEN_EXPIRED]: 401,
  [UJAMAADAO_ERROR_CODES.TOKEN_INVALID]: 401,
  [UJAMAADAO_ERROR_CODES.WALLET_SIGNATURE_INVALID]: 401,

  // 403s - Authorization
  [UJAMAADAO_ERROR_CODES.AUTHORIZATION_ERROR]: 403,
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_VERIFICATION]: 403,
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_IMPACT_POINTS]: 403,
  [UJAMAADAO_ERROR_CODES.GEOGRAPHIC_ERROR]: 403,
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_GEOGRAPHIC_SCOPE]: 403,
  [UJAMAADAO_ERROR_CODES.GEOGRAPHIC_IDENTIFIER_MISMATCH]: 403,
  [UJAMAADAO_ERROR_CODES.MISSING_GEOGRAPHIC_CONTEXT]: 403,
  [UJAMAADAO_ERROR_CODES.ECONOMIC_ERROR]: 403,
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_TOKENS]: 403,
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_PARTICIPATION_RIGHTS]: 403,
  [UJAMAADAO_ERROR_CODES.RESIDENCE_CHANGE_COOLDOWN]: 403,

  // 404s - Not Found
  [UJAMAADAO_ERROR_CODES.NOT_FOUND]: 404,

  // 409s - Conflict
  [UJAMAADAO_ERROR_CODES.CONFLICT]: 409,
  [UJAMAADAO_ERROR_CODES.DUPLICATE_RESOURCE]: 409,

  // 429 - Rate Limiting
  [UJAMAADAO_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,

  // 500s - Server errors
  [UJAMAADAO_ERROR_CODES.SYSTEM_ERROR]: 500,
  [UJAMAADAO_ERROR_CODES.DATABASE_ERROR]: 500,
  [UJAMAADAO_ERROR_CODES.TRANSACTION_FAILED]: 500,
  [UJAMAADAO_ERROR_CODES.WALLET_ERROR]: 500,
  [UJAMAADAO_ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 502,
};

/**
 * User-friendly error messages for each code
 */
export const ERROR_CODE_MESSAGES: Record<UjamaadaoErrorCode, string> = {
  // Validation
  [UJAMAADAO_ERROR_CODES.VALIDATION_ERROR]: 'The provided data is invalid',
  [UJAMAADAO_ERROR_CODES.INVALID_INPUT]: 'Invalid input provided',
  [UJAMAADAO_ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Required field is missing',

  // Authentication
  [UJAMAADAO_ERROR_CODES.AUTHENTICATION_ERROR]: 'Authentication required',
  [UJAMAADAO_ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid credentials provided',
  [UJAMAADAO_ERROR_CODES.TOKEN_EXPIRED]: 'Your session has expired',
  [UJAMAADAO_ERROR_CODES.TOKEN_INVALID]: 'Invalid authentication token',
  [UJAMAADAO_ERROR_CODES.WALLET_SIGNATURE_INVALID]: 'Invalid wallet signature',

  // Authorization
  [UJAMAADAO_ERROR_CODES.AUTHORIZATION_ERROR]: 'You do not have permission to perform this action',
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_VERIFICATION]: 'Your account verification level is insufficient',
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_IMPACT_POINTS]: 'Insufficient impact points',
  [UJAMAADAO_ERROR_CODES.RESIDENCE_CHANGE_COOLDOWN]: 'Residence change is on cooldown',

  // Geographic
  [UJAMAADAO_ERROR_CODES.GEOGRAPHIC_ERROR]: 'Geographic operation failed',
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_GEOGRAPHIC_SCOPE]: 'Insufficient geographic scope',
  [UJAMAADAO_ERROR_CODES.GEOGRAPHIC_IDENTIFIER_MISMATCH]: 'Geographic identifier mismatch',
  [UJAMAADAO_ERROR_CODES.MISSING_GEOGRAPHIC_CONTEXT]: 'Missing geographic context',

  // Economic
  [UJAMAADAO_ERROR_CODES.ECONOMIC_ERROR]: 'Economic operation failed',
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_TOKENS]: 'Insufficient tokens',
  [UJAMAADAO_ERROR_CODES.TRANSACTION_FAILED]: 'Transaction failed',
  [UJAMAADAO_ERROR_CODES.WALLET_ERROR]: 'Wallet operation failed',
  [UJAMAADAO_ERROR_CODES.INSUFFICIENT_PARTICIPATION_RIGHTS]: 'Insufficient Participation Rights (PR) to perform this action',

  // Resources
  [UJAMAADAO_ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [UJAMAADAO_ERROR_CODES.CONFLICT]: 'Resource conflict',
  [UJAMAADAO_ERROR_CODES.DUPLICATE_RESOURCE]: 'Resource already exists',

  // System
  [UJAMAADAO_ERROR_CODES.SYSTEM_ERROR]: 'An unexpected error occurred',
  [UJAMAADAO_ERROR_CODES.DATABASE_ERROR]: 'Database operation failed',
  [UJAMAADAO_ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service unavailable',
  [UJAMAADAO_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests',
};