/**
 * @file src/modules/audit/types.ts
 * @description
 * Audit Module Types
 * Version: 2.0 — December 2025
 */

export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  RESIDENCE_CHANGE_REQUESTED = 'RESIDENCE_CHANGE_REQUESTED',
  RESIDENCE_CHANGE_APPROVED = 'RESIDENCE_CHANGE_APPROVED',
  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_JOINED = 'GROUP_JOINED',
  GROUP_LEFT = 'GROUP_LEFT',
  PROPOSAL_CREATED = 'PROPOSAL_CREATED',
  PROPOSAL_VOTE_CAST = 'PROPOSAL_VOTE_CAST',
  PROPOSAL_STATUS_CHANGED = 'PROPOSAL_STATUS_CHANGED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  MILESTONE_SUBMITTED = 'MILESTONE_SUBMITTED',
  MILESTONE_VERIFIED = 'MILESTONE_VERIFIED',
  DUES_PAID = 'DUES_PAID',
  COMMITMENT_CREATED = 'COMMITMENT_CREATED',
  PR_AWARDED = 'PR_AWARDED',
  PR_SPENT = 'PR_SPENT',
  PR_INACTIVITY_DECAY = 'PR_INACTIVITY_DECAY',
  IP_AWARDED = 'IP_AWARDED',
  EMERGENCY_REPORTED = 'EMERGENCY_REPORTED',
  WORK_LOGGED = 'WORK_LOGGED',
  WORK_VERIFIED = 'WORK_VERIFIED',
  LISTING_CREATED = 'LISTING_CREATED',
  LISTING_DEACTIVATED = 'LISTING_DEACTIVATED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REVOKED = 'ROLE_REVOKED',
  MODULE_PUBLISHED = 'MODULE_PUBLISHED',
  UT_WITHDRAWAL_REQUESTED = 'UT_WITHDRAWAL_REQUESTED',
  ELECTION_CREATED = 'ELECTION_CREATED',
  ELECTION_NOMINATION_SUBMITTED = 'ELECTION_NOMINATION_SUBMITTED',
  ELECTION_NOMINATION_WITHDRAWN = 'ELECTION_NOMINATION_WITHDRAWN',
  ELECTION_VOTE_CAST = 'ELECTION_VOTE_CAST',
  ELECTION_CLOSED = 'ELECTION_CLOSED',
  ELECTION_ROLE_APPLIED = 'ELECTION_ROLE_APPLIED',
  GROUP_DISSOLVED = 'GROUP_DISSOLVED',
  CONFLICT_FILED = 'CONFLICT_FILED',
  CONFLICT_RESOLVED = 'CONFLICT_RESOLVED',
}

export interface AuditSearchDto {
  userId?: string;
  action?: AuditAction;
  entityType?: string;
  entityId?: string;
  fromDate?: string;
  toDate?: string;
  page?: number;
  limit?: number;
  sortBy?: 'createdAt' | 'action';
  sortOrder?: 'asc' | 'desc';
}
