/**
 * @file src/modules/reputation/types.ts
 * @description
 * Impact Points Types & Constants
 * Version: 2.0 — December 2025
 */

export enum ImpactPointReason {
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  COMMUNITY_VERIFIED = 'COMMUNITY_VERIFIED',
  TEMPORARY_CHECKIN = 'TEMPORARY_CHECKIN',
  EDUCATION_MODULE_COMPLETED = 'EDUCATION_MODULE_COMPLETED',
  PHYSICAL_WORK_VERIFIED = 'PHYSICAL_WORK_VERIFIED',
  MILESTONE_ACHIEVED = 'MILESTONE_ACHIEVED',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  // Governance
  VOTE_CAST = 'VOTE_CAST',
  PROPOSAL_PASSED = 'PROPOSAL_PASSED',
  // Community participation
  CONFLICT_FILED = 'CONFLICT_FILED',
  CONFLICT_RESOLVED = 'CONFLICT_RESOLVED',
  VOUCHED_FOR_MEMBER = 'VOUCHED_FOR_MEMBER',
  GROUP_CREATED = 'GROUP_CREATED',
  // Project
  PROJECT_JOINED = 'PROJECT_JOINED',
  PROJECT_CONTRIBUTED = 'PROJECT_CONTRIBUTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
}

export const IP_CONFIG = {
  DECAY_MONTHLY_RATE: 0.1, // 10% decay
  DECAY_ACTIVE_USER_RATE: 0.05, // 5% if active
  DECAY_GRACE_MONTHS: 3, // No decay first 3 months
  ACTIVE_DAYS_THRESHOLD: 30,
} as const;

export const LOCATION_TIER_THRESHOLDS = {
  BRONZE: 100,
  SILVER: 500,
  GOLD: 2000,
  PLATINUM: 5000,
} as const;
